Style/Encoding:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/EmptyCaseCondition:
  Enabled: false
Metrics/MethodLength:
  Max: 10
Metrics/AbcSize:
  Enabled: false
